name: "change file"
on:
  pull_request:
    branches:
      - main
    types: [closed]
    paths:
      - 'values/values-*.yaml'
  workflow_dispatch:

jobs:
  change-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: Identify added file
      id: identify_file
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        echo "name=files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | xargs)" >> $GITHUB_OUTPUT

    - name: List all changed files
      run: | 
          echo ${{ steps.identify_file.outputs.files }}
          

          
          
    
