name: "change file"
on:
  pull_request:
    branches:
      - main
    types: [closed]
    paths:
      - 'values/values-*.yaml'
  workflow_dispatch:

jobs:
  change-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: Identify added file
      id: identify_file
      uses: tj-actions/changed-files@v45

    - name: List all changed files
      env:
        ALL_CHANGED_FILES: ${{ steps.identify_file.outputs.all_changed_files }}
      run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done
    
