name: Use Environment Variable

on:
 workflow_dispatch:


jobs:
  use-env-variable:
    runs-on: ubuntu-latest
    environment: test

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print TEST_URL environment variable
      run: |
        echo "The value of TEST_URL is: ${{ env.TEST_URL }}"
